spring:
  # datasource \u6570\u636E\u6E90\u914D\u7F6E\u5185\u5BB9\uFF0C\u5BF9\u5E94 DataSourceProperties \u914D\u7F6E\u5C5E\u6027\u7C7B
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lab-test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    username: root # \u6570\u636E\u5E93\u8D26\u53F7
    password: root # \u6570\u636E\u5E93\u5BC6\u7801
  # Liquibase \u914D\u7F6E\u5185\u5BB9\uFF0C\u5BF9\u5E94 LiquibaseProperties \u914D\u7F6E\u9879
  liquibase:
    enabled: true # \u5F00\u542F Liquibase \u529F\u80FD\u3002\u9ED8\u8BA4\u4E3A true \u3002
    change-log: classpath:/db/liqiubase/master.xml # Liquibase \u914D\u7F6E\u6587\u4EF6\u5730\u5740
    url: jdbc:mysql://127.0.0.1:3306/lab-test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai # \u6570\u636E\u5E93\u5730\u5740
    user: root # \u6570\u636E\u5E93\u8D26\u53F7
    password: root # \u6570\u636E\u5E93\u5BC6\u7801
