spring:
  # datasource  数据源配置内容
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/learn_db?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

# mybatis-plus 配置内容
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 虽然默认为 true ，但是还是显示去指定下。
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: true
    db-config:
      id-type: auto
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.cn.coder.lab02mybatisplus.entity

